    export const statsVocab = [
    'probability',
    'Calculus',
    'integer',
    'prime',
    'coefficient',
    'binary',
    'Boolean',
    'Slope',
    'Velocity',
    'Volume',
    'Absolute value',
    'Derivative',
    'Integral',
    'Definite integral',
    'Logarithmic',
    'Conditional probability', 
    'standard deviation', 
    'Binomial theorem', 
    'Binomial distribution', 
    'Frequency distribution'
]
    export const bioVocab = [
        'biology',
        'biodiversity',
        'food chain',
        'pollution',
        'DNA',
        'chromosome',
        'organism', 
        'algae',
        'barnacle',
        'coral',
        'crustacean',
        'mammal',
        'mitochondria',
        'homeostasis',
        'cellular respiration',
        'mitosis',
        'nucleus', 
        'enzyme', 
        'permeable',
        'atom'
]
    export const englishVocab = [
        'literacy',
        'grammar',
        'diction',
        'figurative',
        'hyperbole',
        'irony',
        'oxymoron',
        'alliteration',
        'rhyme',
        'prose',
        'metaphor',
        'epithet',
        'allegory',
        'vignette',
        'analysis', 
        'topic sentence', 
        'theme',
        'narrative',
        'climax'
]
    export const techVocab = [
        'application',
        'search engine', 
        'WiFi', 
        'bandwidth', 
        'software', 
        'interface', 
        'operating system',
        'database', 
        'Code', 
        'algorithm', 
        'cache', 
        'Hardware', 
        'scanner', 
        'Harddrive', 
        'byte', 
        'keyboard'
]